### ISSUE TITLE
System.lO.FileNotFoundException:

### ISSUE THREAD

**Issue by 5616760** [ADN-DevTech/RevitTrainingMaterial#14]
有人遇到这个问题吗？一点生成代码就这样：System.lO.FileNotFoundException:
未能加载文件或程序集'System.Runtime.CompilerServices.Unsafe,
Version=4.0.4.1, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a
"或它的某一 个依赖项。系统找不到指定的文件。

**Comment by jeremytammik** [comment]
No. Have you successfully completed the My First Plug-in Tutorial, or implemented one of the Hello World samples in the developer guide? Maybe that would be easier to start with, and avoid the problem you encountered. 

- https://thebuildingcoder.typepad.com/blog/about-the-author.html#2
- https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/7I2bC1zUr4VjJ3U31uM66K.html
- https://help.autodesk.com/view/RVT/2024/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Introduction_Getting_Started_Walkthroughs_html

**Comment by 5616760** [comment]
> No. Have you successfully completed the My First Plug-in Tutorial, or implemented one of the Hello World samples in the developer guide? Maybe that would be easier to start with, and avoid the problem you encountered.
> 
> * https://thebuildingcoder.typepad.com/blog/about-the-author.html#2
> * https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/7I2bC1zUr4VjJ3U31uM66K.html
> * https://help.autodesk.com/view/RVT/2024/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Introduction_Getting_Started_Walkthroughs_html

Thanks for your reply！
